[package]
name = "st"
version = "0.1.0"
authors = ["QiYuTech <admin@qiyutech.tech>"]
edition = "2018"

[[bin]]
name = "st"
path = "src/bins/main.rs"

[dependencies]
structopt = "0.3"

which = "4.0"

serde = { version = "1.0", features = ["derive"] }

toml = "0.5"

serde_json = "1.0"

