name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      # upload unix
      - uses: actions/upload-artifact@v2
        if: strategy != 'windows-latest'
        with:
          name: ${{ matrix.os }}
          path: target/debug/st
      # upload windows
      - uses: actions/upload-artifact@v2
        if: strategy == 'windows-latest'
        with:
          name: ${{ matrix.os }}
          path: target/debug/st.exe
